# Generated by Django 5.2.4 on 2025-09-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Bathroom', 'Kitchen'", max_length=100, verbose_name='Title')),
                ('image', models.ImageField(upload_to='cleaning_areas/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers are displayed first.', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Cleaning Area',
                'verbose_name_plural': 'Cleaning Areas',
                'ordering': ['order'],
            },
        ),
    ]
