# Generated by Django 5.2.4 on 2025-09-28 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('position_x', models.FloatField(default=50.0, help_text='Horizontal position from left to right, in percent (e.g., 25.5)', verbose_name='Position X (%)')),
                ('position_y', models.FloatField(default=50.0, help_text='Vertical position from top to bottom, in percent (e.g., 70)', verbose_name='Position Y (%)')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_points', to='core.cleaningarea', verbose_name='Cleaning Area')),
            ],
        ),
    ]
