# Generated by Django 5.2.4 on 2025-10-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_featurepoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=50.0, help_text='The fee charged for cancellations made less than 24 hours in advance.', max_digits=10, verbose_name='Cancellation Fee (zł)')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
