# Generated by Django 5.2.4 on 2025-10-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningarea',
            name='title_en',
            field=models.CharField(help_text="e.g., 'Bathroom', 'Kitchen'", max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='cleaningarea',
            name='title_pl',
            field=models.CharField(help_text="e.g., 'Bathroom', 'Kitchen'", max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='cleaningarea',
            name='title_ru',
            field=models.CharField(help_text="e.g., 'Bathroom', 'Kitchen'", max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='cleaningarea',
            name='title_uk',
            field=models.CharField(help_text="e.g., 'Bathroom', 'Kitchen'", max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='featurepoint',
            name='description_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='featurepoint',
            name='description_pl',
            field=models.CharField(max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='featurepoint',
            name='description_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='featurepoint',
            name='description_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='telegram_link',
            field=models.URLField(blank=True, help_text='Full URL to the Telegram account, e.g., https://t.me/your_account', max_length=255, null=True, verbose_name='Telegram Link'),
        ),
    ]
