# Generated by Django 4.2.25 on 2025-11-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cleaningarea_title_en_cleaningarea_title_pl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='services_page_enabled',
            field=models.BooleanField(default=True, help_text="Если флаг выключен, ссылка на страницу 'Услуги' исчезнет из навигации сайта.", verbose_name="Показывать страницу 'Услуги'"),
        ),
    ]
