# Generated by Django 4.2.25 on 2025-12-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteconfiguration_services_page_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name for admin, e.g., 'New Year 2026'", max_length=100, verbose_name='Banner Name')),
                ('content_type', models.CharField(choices=[('image', 'Image (PNG, JPG, GIF)'), ('video', 'Video (MP4, WebM)'), ('lottie', 'Lottie Animation (JSON)'), ('text_only', 'Text Only')], default='image', max_length=20, verbose_name='Content Type')),
                ('image', models.ImageField(blank=True, help_text='Upload image or animated GIF', null=True, upload_to='promo_banners/', verbose_name='Image / GIF')),
                ('video_file', models.FileField(blank=True, help_text='Upload MP4 or WebM video', null=True, upload_to='promo_banners/videos/', verbose_name='Video File')),
                ('lottie_json', models.FileField(blank=True, help_text='Upload Lottie JSON file', null=True, upload_to='promo_banners/lottie/', verbose_name='Lottie Animation')),
                ('title', models.CharField(blank=True, help_text='Holiday greeting or promo title', max_length=200, verbose_name='Title')),
                ('title_pl', models.CharField(blank=True, help_text='Holiday greeting or promo title', max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, help_text='Holiday greeting or promo title', max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(blank=True, help_text='Holiday greeting or promo title', max_length=200, null=True, verbose_name='Title')),
                ('title_uk', models.CharField(blank=True, help_text='Holiday greeting or promo title', max_length=200, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Additional text or message', verbose_name='Description')),
                ('description_pl', models.TextField(blank=True, help_text='Additional text or message', null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, help_text='Additional text or message', null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, help_text='Additional text or message', null=True, verbose_name='Description')),
                ('description_uk', models.TextField(blank=True, help_text='Additional text or message', null=True, verbose_name='Description')),
                ('link', models.URLField(blank=True, help_text='Optional: URL to open when banner is clicked', null=True, verbose_name='Link URL')),
                ('link_text', models.CharField(blank=True, default='', help_text="Text for the button, e.g., 'Learn more'", max_length=50, verbose_name='Link Button Text')),
                ('link_text_pl', models.CharField(blank=True, default='', help_text="Text for the button, e.g., 'Learn more'", max_length=50, null=True, verbose_name='Link Button Text')),
                ('link_text_en', models.CharField(blank=True, default='', help_text="Text for the button, e.g., 'Learn more'", max_length=50, null=True, verbose_name='Link Button Text')),
                ('link_text_ru', models.CharField(blank=True, default='', help_text="Text for the button, e.g., 'Learn more'", max_length=50, null=True, verbose_name='Link Button Text')),
                ('link_text_uk', models.CharField(blank=True, default='', help_text="Text for the button, e.g., 'Learn more'", max_length=50, null=True, verbose_name='Link Button Text')),
                ('start_date', models.DateTimeField(blank=True, help_text='When to start showing the banner. Leave empty to show immediately.', null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, help_text='When to stop showing the banner. Leave empty to show indefinitely.', null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this banner', verbose_name='Active')),
                ('show_border', models.BooleanField(default=True, help_text='Show decorative border around the banner', verbose_name='Show Border')),
                ('border_style', models.CharField(choices=[('gold', 'Gold (default)'), ('festive', 'Festive (animated)'), ('minimal', 'Minimal'), ('none', 'No border')], default='gold', max_length=20, verbose_name='Border Style')),
                ('background_color', models.CharField(blank=True, default='', help_text="CSS color, e.g., '#ffffff' or 'transparent'", max_length=20, verbose_name='Background Color')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number = higher priority. Banner with highest priority will be shown.', verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo Banner',
                'verbose_name_plural': 'Promo Banners',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='whatsapp_link',
            field=models.URLField(blank=True, help_text='Full URL to WhatsApp, e.g., https://wa.me/48781628269', max_length=255, null=True, verbose_name='WhatsApp Link'),
        ),
    ]
