# Generated by Django 5.2.4 on 2025-08-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title / Description')),
                ('title_pl', models.CharField(max_length=100, null=True, verbose_name='Title / Description')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title / Description')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Title / Description')),
                ('title_uk', models.CharField(max_length=100, null=True, verbose_name='Title / Description')),
                ('before_image', models.ImageField(upload_to='gallery/before/', verbose_name="'Before' Image")),
                ('after_image', models.ImageField(upload_to='gallery/after/', verbose_name="'After' Image")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order'],
            },
        ),
    ]
