# Generated by Django 5.2.4 on 2025-08-24 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name="Author's Name")),
                ('author_name_pl', models.CharField(max_length=100, null=True, verbose_name="Author's Name")),
                ('author_name_en', models.CharField(max_length=100, null=True, verbose_name="Author's Name")),
                ('author_name_ru', models.CharField(max_length=100, null=True, verbose_name="Author's Name")),
                ('author_name_uk', models.CharField(max_length=100, null=True, verbose_name="Author's Name")),
                ('text', models.TextField(verbose_name='Review Text')),
                ('text_pl', models.TextField(null=True, verbose_name='Review Text')),
                ('text_en', models.TextField(null=True, verbose_name='Review Text')),
                ('text_ru', models.TextField(null=True, verbose_name='Review Text')),
                ('text_uk', models.TextField(null=True, verbose_name='Review Text')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (1-5)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['order'],
            },
        ),
    ]
