# Generated by Django 5.2.4 on 2025-08-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AlterField(
            model_name='review',
            name='author_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AlterField(
            model_name='review',
            name='author_name_pl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AlterField(
            model_name='review',
            name='author_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Author's Name"),
        ),
        migrations.AlterField(
            model_name='review',
            name='author_name_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Author's Name"),
        ),
    ]
