# Generated by Django 4.2.25 on 2025-11-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='show_date',
            field=models.BooleanField(default=True, help_text='If checked, the creation date will be displayed on the website.', verbose_name='Show Creation Date on Site'),
        ),
    ]
