# Generated by Django 5.2.4 on 2025-07-25 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон клиента')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email клиента')),
                ('customer_address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('rooms_count', models.PositiveIntegerField(default=1, verbose_name='Кол-во комнат')),
                ('bathrooms_count', models.PositiveIntegerField(default=1, verbose_name='Кол-во санузлов')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая стоимость')),
                ('cleaning_date', models.DateField(verbose_name='Дата уборки')),
                ('cleaning_time', models.TimeField(verbose_name='Время уборки')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('additional_services', models.ManyToManyField(blank=True, to='products.additionalservice', verbose_name='Доп. услуги')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.service', verbose_name='Основная услуга')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
