# Generated by Django 5.2.4 on 2025-08-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='frequency',
            field=models.CharField(choices=[('one_time', 'One-time'), ('weekly', 'Weekly'), ('bi_weekly', 'Every 2 weeks'), ('monthly', 'Monthly')], default='one_time', max_length=20, verbose_name='Cleaning Frequency'),
        ),
    ]
