# Generated by Django 5.2.4 on 2025-08-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='window_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Window Count'),
        ),
    ]
