# Generated by Django 5.2.4 on 2025-09-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_window_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bring_vacuum_cleaner',
            field=models.BooleanField(default=False, verbose_name='Bring vacuum cleaner'),
        ),
    ]
