# Generated by Django 5.2.4 on 2025-09-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_bring_vacuum_cleaner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_private_house',
            field=models.BooleanField(default=False, verbose_name='Private House (x1.2)'),
        ),
    ]
