# Generated by Django 5.2.4 on 2025-09-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_is_private_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Estimated duration (minutes)'),
        ),
    ]
