# Generated by Django 5.2.4 on 2025-09-28 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_estimated_duration_minutes'),
        ('products', '0007_additionalservice_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_address',
        ),
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Additional comments'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_address_apartment',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Apartment/Office number'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_address_city',
            field=models.CharField(default='Warszawa', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_address_entrance',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Entrance'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_address_postal_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_address_street',
            field=models.CharField(default='', max_length=255, verbose_name='Street and building number'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='cash', max_length=10, verbose_name='Payment method'),
        ),
        migrations.AddField(
            model_name='order',
            name='sqm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Area (sqm)'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='additional_services',
            field=models.ManyToManyField(blank=True, related_name='additional_in_orders', to='products.service', verbose_name='Additional services'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bathrooms_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of bathrooms'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cleaning_date',
            field=models.DateField(verbose_name='Desired cleaning date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cleaning_time',
            field=models.TimeField(verbose_name='Desired time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimated duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='frequency',
            field=models.CharField(blank=True, default='one_time', max_length=20, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_private_house',
            field=models.BooleanField(default=False, verbose_name='Private house'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rooms_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of rooms'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='products.service', verbose_name='Service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='window_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of windows'),
        ),
    ]
