# Generated by Django 5.2.4 on 2025-09-28 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_customer_address_order_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='City name')),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Delivery charge')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_address_apartment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_address_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_address_entrance',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_address_postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_address_street',
        ),
        migrations.AddField(
            model_name='order',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Apartment number'),
        ),
        migrations.AddField(
            model_name='order',
            name='building_number',
            field=models.CharField(default='', max_length=10, verbose_name='Building number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Delivery charge'),
        ),
        migrations.AddField(
            model_name='order',
            name='entrance',
            field=models.CharField(blank=True, max_length=10, verbose_name='Entrance'),
        ),
        migrations.AddField(
            model_name='order',
            name='floor',
            field=models.CharField(blank=True, max_length=10, verbose_name='Floor'),
        ),
        migrations.AddField(
            model_name='order',
            name='intercom_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Intercom code'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='', max_length=10, verbose_name='Postal code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default='', max_length=255, verbose_name='Street'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.city', verbose_name='City'),
        ),
    ]
