# Generated by Django 5.2.4 on 2025-10-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_load_cities'),
        ('products', '0010_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additional_services',
            field=models.ManyToManyField(blank=True, related_name='additional_in_orders', to='products.additionalservice', verbose_name='Additional services'),
        ),
    ]
