# Generated by Django 4.2.25 on 2025-11-12 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_additionalservice_is_quantity_based'),
        ('orders', '0012_alter_city_options_order_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_services',
        ),
        migrations.AddField(
            model_name='order',
            name='additional_services_details',
            field=models.JSONField(blank=True, default=list, verbose_name='Additional Services Details'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.service', verbose_name='Service'),
        ),
    ]
