# Generated by Django 5.2.4 on 2025-07-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название доп. услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена')),
                ('price_per_room', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за доп. комнату')),
                ('price_per_bathroom', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за доп. санузел')),
            ],
            options={
                'verbose_name': 'Основная услуга',
                'verbose_name_plural': 'Основные услуги',
            },
        ),
    ]
