# Generated by Django 5.2.4 on 2025-08-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalservice',
            options={'verbose_name': 'Additional Service', 'verbose_name_plural': 'Additional Services'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Main Service', 'verbose_name_plural': 'Main Services'},
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Additional Service Name'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='name_pl',
            field=models.CharField(max_length=100, null=True, verbose_name='Additional Service Name'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Additional Service Name'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Additional Service Name'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Service Name'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_pl',
            field=models.CharField(max_length=100, null=True, verbose_name='Service Name'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Service Name'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Additional Service Name'),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_per_bathroom',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per extra bathroom'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_per_room',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per extra room'),
        ),
    ]
