# Generated by Django 5.2.4 on 2025-08-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_additionalservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_sqm_based',
            field=models.BooleanField(default=False, verbose_name='Is Sqm Based?'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_per_sqm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price Per Sqm'),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='name_pl',
            field=models.CharField(max_length=100, null=True, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Service Name'),
        ),
    ]
