# Generated by Django 5.2.4 on 2025-08-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_service_is_sqm_based_service_price_per_sqm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_window_service',
            field=models.BooleanField(default=False, verbose_name='Is Window Cleaning Service?'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_per_sqm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price Per Sqm / Per Window'),
        ),
    ]
