# Generated by Django 5.2.4 on 2025-09-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_service_is_window_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalservice',
            options={'verbose_name': 'Дополнительная услуга', 'verbose_name_plural': 'Дополнительные услуги'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Основная услуга', 'verbose_name_plural': 'Основные услуги'},
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='service_icons/', verbose_name='Icon'),
        ),
    ]
