# Generated by Django 5.2.4 on 2025-09-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_additionalservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='Duration (minutes)'),
        ),
        migrations.AddField(
            model_name='service',
            name='base_duration_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Base duration (minutes)'),
        ),
    ]
