# Generated by Django 5.2.4 on 2025-09-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_additionalservice_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
