# Generated by Django 5.2.4 on 2025-09-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_additionalservice_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservice',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='How many minutes does this service add to the total cleaning time?', verbose_name='Duration (minutes)'),
        ),
    ]
