# Generated by Django 5.2.4 on 2025-09-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_additionalservice_duration_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenCleaningFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('icon', models.FileField(upload_to='kitchen_features_icons/', verbose_name='Icon')),
                ('category', models.CharField(choices=[('wash', 'Wash inside and out'), ('wipe', 'Wipe and clean')], default='wash', max_length=10, verbose_name='Category')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Kitchen Cleaning Feature',
                'verbose_name_plural': 'Kitchen Cleaning Features',
                'ordering': ['category', 'order'],
            },
        ),
    ]
