# Generated by Django 5.2.4 on 2025-09-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_kitchencleaningfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text="A unique slug for the service URL, e.g., 'kitchen-cleaning'", max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
