# Generated by Django 4.2.25 on 2025-11-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='is_for_kitchen',
            field=models.BooleanField(default=False, help_text='Check this if the service should be displayed on the Kitchen Cleaning page.', verbose_name='For Kitchen Cleaning Page'),
        ),
    ]
