# Generated by Django 4.2.25 on 2025-11-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_additionalservice_is_for_kitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Services with a lower number will be displayed first.', verbose_name='Display Order'),
        ),
    ]
