# Generated by Django 4.2.25 on 2025-11-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_additionalservice_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchencleaningfeature',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='kitchencleaningfeature',
            name='title_pl',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='kitchencleaningfeature',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='kitchencleaningfeature',
            name='title_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
    ]
