# Generated by Django 4.2.25 on 2025-11-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_kitchencleaningfeature_title_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalservice',
            options={'ordering': ['order'], 'verbose_name': 'Дополнительная услуга', 'verbose_name_plural': 'Дополнительные услуги'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Основная услуга', 'verbose_name_plural': 'Основные услуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('description_pl', models.CharField(max_length=255, null=True, verbose_name='Description')),
                ('description_en', models.CharField(max_length=255, null=True, verbose_name='Description')),
                ('description_ru', models.CharField(max_length=255, null=True, verbose_name='Description')),
                ('description_uk', models.CharField(max_length=255, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service Feature',
                'verbose_name_plural': 'Service Features',
                'ordering': ['order'],
            },
        ),
    ]
