# Generated by Django 4.2.25 on 2025-11-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_additionalservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, help_text='A brief description for service cards, max 200 characters.', max_length=200, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.TextField(blank=True, help_text='A brief description for service cards, max 200 characters.', max_length=200, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_pl',
            field=models.TextField(blank=True, help_text='A brief description for service cards, max 200 characters.', max_length=200, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_ru',
            field=models.TextField(blank=True, help_text='A brief description for service cards, max 200 characters.', max_length=200, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_uk',
            field=models.TextField(blank=True, help_text='A brief description for service cards, max 200 characters.', max_length=200, null=True, verbose_name='Short Description'),
        ),
    ]
