# Generated by Django 4.2.25 on 2025-11-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_service_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='is_quantity_based',
            field=models.BooleanField(default=False, help_text='If checked, a quantity selector will be shown instead of a checkbox.', verbose_name='Is quantity-based?'),
        ),
    ]
