# Generated by Django 4.2.25 on 2025-11-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_service_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='price_description',
            field=models.CharField(blank=True, help_text="Ex: 'per item', 'per hour'. Leave empty if not needed.", max_length=50, verbose_name='Price Description'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='price_description_en',
            field=models.CharField(blank=True, help_text="Ex: 'per item', 'per hour'. Leave empty if not needed.", max_length=50, null=True, verbose_name='Price Description'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='price_description_pl',
            field=models.CharField(blank=True, help_text="Ex: 'per item', 'per hour'. Leave empty if not needed.", max_length=50, null=True, verbose_name='Price Description'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='price_description_ru',
            field=models.CharField(blank=True, help_text="Ex: 'per item', 'per hour'. Leave empty if not needed.", max_length=50, null=True, verbose_name='Price Description'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='price_description_uk',
            field=models.CharField(blank=True, help_text="Ex: 'per item', 'per hour'. Leave empty if not needed.", max_length=50, null=True, verbose_name='Price Description'),
        ),
    ]
