# Generated by Django 4.2.25 on 2025-12-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_additionalservice_price_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration_per_sqm',
            field=models.PositiveIntegerField(default=0, help_text="Additional minutes per square meter. Only used if 'Is Sqm Based' is checked. E.g., 5 means 100m² adds 500 minutes.", verbose_name='Duration per m² (minutes)'),
        ),
    ]
